/**
 * Every pattern, threshold and cap the smart-diff classifier uses. Nothing in
 * `helpers.ts` restates a literal — a test or a reviewer changes a rule here
 * and only here.
 *
 * Path and diff-stat matching only: no file contents, no index, no model, no
 * network. The same PR classifies the same way on any machine, forever.
 */

// ---- boilerplate: mechanical, generated, vendored, skim-first --------------

/** Exact basenames — a lock file is boilerplate wherever it sits in the tree. */
export const LOCK_FILES = ['package-lock.json', 'pnpm-lock.yaml', 'yarn.lock'] as const;

/**
 * Directory segments whose contents are never hand-read.
 *
 * This overlaps `EXCLUDED_DIRS` in
 * `server/src/modules/repo-intel/constants.ts` on purpose, and is
 * deliberately **not** imported from there — importing another module's
 * `constants.ts` is a `no-cross-module-internals` violation under
 * `pnpm arch:check`, and the two lists answer different questions anyway:
 * repo-intel is deciding what to *parse*, this is deciding what a human
 * should read first. Restated locally so the two can evolve independently.
 */
export const GENERATED_DIR_SEGMENTS = [
  'dist',
  'build',
  'out',
  '.next',
  'coverage',
  'vendor',
  'node_modules',
] as const;

/** Snapshot output — regenerated by a test run, never hand-written. */
export const SNAPSHOT_PATTERNS: readonly RegExp[] = [/(^|\/)__snapshots__\//, /\.snap$/i];

/** Explicit "this file was generated" markers, plus minified/sourcemap output. */
export const GENERATED_FILE_PATTERNS: readonly RegExp[] = [
  /\.min\.js$/i,
  /\.map$/i,
  /\.gen\./i,
  /\.generated\./i,
];

/**
 * Prose docs — not generated, but skim-first and with no better home in a
 * three-role enum. Matches a `.md` extension or anything under a `docs/`
 * directory.
 */
export const DOC_PATTERNS: readonly RegExp[] = [/\.md$/i, /(^|\/)docs\//i];

/**
 * Generated SQL: anything under a `migrations/` directory segment. A
 * hand-written `.sql` elsewhere is `core`, not boilerplate.
 */
export const MIGRATIONS_SQL_PATTERN = /(^|\/)migrations\/.*\.sql$/i;

/** Binary and asset extensions — nothing here is reviewed line by line. */
export const BINARY_ASSET_EXTENSIONS = [
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.svg',
  '.ico',
  '.webp',
  '.bmp',
  '.woff',
  '.woff2',
  '.ttf',
  '.eot',
  '.pdf',
  '.zip',
  '.mp4',
  '.mov',
  '.mp3',
  '.wav',
] as const;

// ---- wiring: real code, but it connects the change rather than being it ----

/** Barrel files — exported from `dist/`'s equivalent source location. */
export const WIRING_BARRELS = ['index.ts', 'index.tsx'] as const;

/** Process entrypoints. */
export const WIRING_ENTRYPOINTS = ['server.ts', 'app.ts', 'main.ts'] as const;

/**
 * Config, manifests and CI/compose wiring: `config.*` / `*.config.*`,
 * `package.json`, `.env.example`, GitHub Actions workflow YAML, and Docker
 * Compose files.
 */
export const WIRING_CONFIG_PATTERNS: readonly RegExp[] = [
  /(^|\/)config\.[^/]+$/i,
  /(^|\/)[^/.]+\.config\.[^/]+$/i,
  /(^|\/)package\.json$/,
  /(^|\/)\.env\.example$/,
  /(^|\/)\.github\/workflows\/.+\.ya?ml$/i,
  /(^|\/)docker-compose(\.[\w-]+)?\.ya?ml$/i,
];

// ---- split suggestion --------------------------------------------------

/** Above this many changed lines (all files, boilerplate included), too_big. */
export const SPLIT_LINES_MAX = 400;
/** Above this many changed files, too_big — independently of line count. */
export const SPLIT_FILES_MAX = 20;
/** Splits shown before the remainder is folded into `FALLBACK_SPLIT_NAME`. */
export const MAX_PROPOSED_SPLITS = 4;
/** Name of the split holding everything past `MAX_PROPOSED_SPLITS`. */
export const FALLBACK_SPLIT_NAME = 'everything else';
/** Name of the split for a file with no directory (repo root). */
export const ROOT_SPLIT_NAME = 'root';

// ---- the on-demand summary (Task 6) -----------------------------------

/** A patch longer than this is truncated before it reaches the model. */
export const MAX_PATCH_CHARS = 8000;
/** A returned summary longer than this is sliced before it is persisted. */
export const MAX_SUMMARY_CHARS = 280;
